<div id="dlgFamilias" class="dialog">
  <i class="fnClose" title="Salir"></i>
  <h1>Edicion de Familias</h1>
  <hr>
  <form  id="frmEditarFamilia">
    <input type="hidden" id="id" name="id">
    <input type="text" id="nombre" name="nombre" placeholder="nombre de la familia">
     
    <label for="mostrar"> 
	  	<input id="mostrar" type="checkbox" name="mostrar" >
      <span id="lblMostrarFamilia">Mostrar a los clientes</span>
	  </label>
    
      <button type="button" class="btn-success btnLoad aceptar" id="btnAceptar" data-value="Guardar">Guardar</button>
      <button type="button" class="btn-danger btnLoad cancelar" id="btnEliminar" data-value="Eliminar">Eliminar</button>

  </form>
</div> 
