<div id="dlgHistorial" class="dialog">
	<i class="fnClose" title="Salir"></i>
	<div class="content-popup">
		<select name="" id="ultimosServicios">
			<option value="10" selected>mostrar 10</option>
			<option value="20">mostrar 20</option>
			<option value="50">mostrar 50</option>
		</select>
		<br>
		<table class="">
			<thead>
				<tr class = "encabezado">
					<th>Opc</th><th>Agenda</th><th>Fecha/Hora</th>
				</tr>
				<tr id="hisCita" class="template hisCita">
					<td class="hisicon"><span class ="icon-search fnBuscarCita" tittle = "Ir a la cita" ></span></td>
					<td class="hisAgenda"></td>
					<td class="hisFecha"></td>
				</tr>
				<tr id="hisServicios" class="template hisServicios">
					<td><i class="icon-angle-right"></i></td>
					<td colspan=4 class="hisServicio"></td>
				</tr>
				
			</thead>
		</table>
	</div>
</div>