<div  class="dialog " id="dlgCliente" >
  <span class="icon-cancel"></span>
  <h1 class="heading">Guardar cliente</h1>
  <hr>
  <p>nombre cliente no encontrado</p>
  <p>¿Desea guardar el nuevo cliente?</p>

  <p class="submit">
    <input type="button" value="Cancelar" class="btn-danger cancelar" id="btnCancelarDlg">
    <button type="button" class="btn-success btnLoad" id="btnGuardarCliente" data-value="Guardar"></button>
  </p>
  <span class="info">Se aconseja acompañar de un asterisco a los nombres genericos (Maria*,Pedro*,..)</span>
</div>
