<div  class="dialog" id="dlgCambiarPass" >
	<span class="icon-cancel fnClose"></span>
	<h1>Cambiar contraseña</h1>
	<div class="iconClass-container icon-right">
		<input type="password" id="oldPass" name="oldPass" placeholder="Contraseña actual" required>
		<span class="iconClass-inside left icon-eye"></span>
	</div>
	<div class="iconClass-container icon-right">
		<input type="password" id="pass" name="pass" placeholder="Nueva contraseña" require>
		<span class="iconClass-inside icon-eye"></span>
	</div>
	<div class="iconClass-container icon-right">
		<input type="password" id="repeatPass" name="repeatPass" placeholder="Repita la contraseña" required>
		<span class="iconClass-inside left icon-eye"></span>
	</div>
	<button type="button" class="btn-success btnLoad aceptar" data-value="Guardar">Guardar</button>
</div>