<div  class="dialog " id="dlgCliente" >
  <span class="icon-cancel"></span>
  <h1 class="heading">Guardar cliente</h1>
  <hr>
  <p>nombre cliente no encontrado</p>
  <p>¿Desea guardar el nuevo cliente?</p>

  <button type="button" class="btn-danger cancelar" id="btnCancelarCliente" data-value="Cancelar">Cancelar</button>
  <button type="button" class="btn-success btnLoad" id="btnGuardarCliente" data-value="Guardar">Guardar</button>
  
  <span class="info">Se aconseja acompañar de un asterisco a los nombres genericos (Maria*,Pedro*,..)</span>
</div>
