<div  class="dialog" id="dlgEditCita">
	<span class="icon-cancel fnClose"></span>
		<h1>Editando...</h1>
		<hr>
		<div class="template" >
			<span class="icon-cancel-circled fnDelSer"></span>
			<span class='codigo'></span>
			<span class='descripcion'></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="text" class="txt" id="id" readonly>
			<span class="iconClass-inside  icon-angle-right"></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="search" class="txt" id='cliente' list='lstClientes' >
			<span class="iconClass-inside icon-user"></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="date" class="txt" id="fecha"  >
			<span class="iconClass-inside  icon-calendar"></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="time" class="txt" id="hora" step="900" >
			<span class="iconClass-inside  icon-clock"></span>
		</div>
		<div class="iconClass-container icon-left">
			<div class="iconClass-container icon-left">
				<input type="text" class="txt" id="obs" placeholder="Escribe una nota" >
				<span class="iconClass-inside  icon-note"></span>
			</div>
		</div>
		<div id= "codigos"  class="iconClass-container icon-left lst"></div>
		<div id= "newCodigo"  class="iconClass-container icon-left">
			<select name="" id="lstServ">
				<option value='' disabled selected hidden>Añadir servicios</option>
				<?php 
				foreach($_SESSION['SERVICIOS'] as $ser){
					// 0 Id 1 codigo 2 descripcion 3 Precio 4 tiempo 5 IdFamilia 6 Baja
					?>
					<option value="<?=$ser[0] ?>" codigo ="<?=$ser[1] ?>" tiempo="<?=$ser[4]?>"> <?=$ser[2] ?></option>
					<?php
				}
				?>
			</select>
		<div class="iconClass-container icon-left">
			<div class="iconClass-container icon-left">
				<input type="number" class="txt" id="tiempoServicios" >
				<span class="iconClass-inside  icon-clock"></span>
			</div>
		</div>
		</div>
		<button type="button" class="btn-success btnLoad" data-value="Guardar">Guardar</button>
		<button type="button" class="btn-danger btnLoad" data-value="Eliminar">Eliminar</button>
	</div>
</div>