<div  class="dialog" id="dlgEditCita">
	<span class="icon-cancel fnClose"></span>
		<h1>Editando...</h1>
		<hr>
		<div class="template" >
			<span class="icon-cancel-circled fnDelSer"></span>
			<span class='codigo'></span>
			<span class='descripcion'></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="text" class="txt" id="id" readonly>
			<span class="iconClass-inside  icon-angle-right"></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="search" class="txt" id='cliente' list='lstClientes' >
			<span class="iconClass-inside icon-user"></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="date" class="txt" id="fecha"  >
			<span class="iconClass-inside  icon-calendar"></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="time" class="txt" id="hora"  >
			<span class="iconClass-inside  icon-clock"></span>
		</div>
		<div class="iconClass-container icon-left">
			<div class="iconClass-container icon-left">
				<input type="text" class="txt" id="obs" >
				<span class="iconClass-inside  icon-note"></span>
			</div>
		</div>
		<div id= "codigos"  class="iconClass-container icon-left lst"></div>
		<div id= "newCodigo"  class="iconClass-container icon-left">
			<select name="" id="lstServ">
				<option value='' disabled selected hidden>Añadir servicios</option>
				<?php 
				$class_servicios = new core\BaseClass('servicios') ;
				$servicies = $class_servicios->getAll( '*' , MYSQLI_ASSOC) ;
				foreach($servicies as $service){
					?>
					<option value="<?=$service['id'] ?>" codigo ="<?=$service['codigo'] ?>" tiempo="<?=$service['tiempo']?>"> <?=$service['descripcion'] ?></option>
					<?php
				}
				?>
			</select>
		</div>
		<button type="button" class="btn-danger btnLoad" data-value="Eliminar"></button>
		<button type="button" class="btn-success btnLoad" data-value="Guardar"></button>
	</div>
</div>