<div  class="dialog" id="dlgEditCita">
	<i class="fnClose" title="Salir"></i>
		<h1>Editando...</h1>
		<hr>
		<div class="template" >
			<i class="icon-cancel-circled fnDelSer"></i>
			<span class='codigo'></span>
			<span class='descripcion'></span>
		</div>
		<div class="iconClass-container icon-left">
			<span class='caption'>Id cita</span>
			<input type="text" class="txt" id="id" readonly>
			<i class="iconClass-inside  icon-angle-right"></i>
		</div>
		<div class="iconClass-container icon-left">
			<span class='caption'>Nombre cliente</span>
			<input type="search" class="txt" id='cliente' list='lstClientes' >
			<i class="iconClass-inside icon-user"></i>
		</div>
		<div class="iconClass-container icon-left">
			<span class='caption'>Fecha</span>
			<input type="date" class="txt" id="fecha"  >
			<i class="iconClass-inside  icon-calendar"></i>
		</div>
		<div class="iconClass-container icon-left">
			<span class='caption'>Hora</span>
			<input type="time" class="txt" id="hora" step="900" >
			<i class="iconClass-inside  icon-clock"></i>
		</div>
		<div class="iconClass-container icon-left">
			<span class='caption'>Observaciones</span>
			<input type="text" class="txt" id="obs" placeholder="Escribe una nota" >
			<i class="iconClass-inside  icon-note"></i>
		</div>
		<div id= "codigos"  class="iconClass-container icon-left lst"></div>
		<div id= "newCodigo"  class="iconClass-container icon-left">
			<span class='caption'>Servicios</span>
			<select name="" id="lstServ">
				<option value='' disabled selected hidden>Añadir servicios</option>
				<?php 
				foreach($_SESSION['SERVICIOS'] as $ser){
					// 0 Id 1 codigo 2 descripcion 3 Precio 4 tiempo 5 IdFamilia 6 Baja
					?>
					<option value="<?=$ser[0] ?>" codigo ="<?=$ser[1] ?>" tiempo="<?=$ser[4]?>"> <?=$ser[2] ?></option>
					<?php
				}
				?>
			</select>
		</div>
		<div class="iconClass-container icon-left">
			<span class='caption'>Tiempo total servicios</span>
			<input type="number" class="txt" id="tiempoServicios" >
			<i class="iconClass-inside  icon-clock"></i>
		</div>
		<button type="button" class="btn-success btnLoad" data-value="Guardar">Guardar</button>
		<button type="button" class="btn-danger btnLoad" data-value="Eliminar">Eliminar</button>
	</div>
</div>