<div id="dlgFestivos" class="dialog">
	<i class="fnClose" title="Salir"></i>
		<h1 class="heading">Añadir festivo</h1>
		<hr>
		<form  id="frmEditarFestivos">
			<input type="hidden" id="id" class="txt" name="id" readonly>
			<div class="iconClass-container icon-left">
				<input type="text" class="txt" id="nombre" placeholder="Introduzca el nombre" 
					alt="Introduzca el nombre"  autocomplete="off" maxlength="10" required>
				<span class="iconClass-inside  icon-angle-right"></span>
			</div>
			<div class="iconClass-container icon-left">
				<input type="date" class="txt" id="fecha" placeholder="Introduzca la fecha" 
					alt="Introduzca el fecha" autocomplete="off" required>
				<span class="iconClass-inside icon-calendar"></span>
			</div>
			

			<button type="button" class="btn-success btnLoad aceptar"  id="btnAceptar" data-value="Guardar">Guardar</button>
			<button type="button" class="btn-danger btnLoad cancelar" id="btnEliminar" data-value="Eliminar">Eliminar</button>
		</form>
</div>