<div class="dialog" id="dlgGuardar">
	<span class="icon-cancel"></span>
	<div class="dialog-content">
		<h1>Guardando...</h1>
		<hr>
		<form>
			<table id="tblGuardarCita">
				<tr class="aling-left">
					<td>Reservar a: </td>
					<td><span id="lblCliente" class="resaltado"></span></td>
				</tr >
				<tr class="aling-left">
					<td>los servicios: </td>
					<td><span id="lblSer" class="resaltado"></span></td>
				</tr>
				<tr class="aling-left">
					<td>el: </td>
					<td><span  id="lblfecha" class="resaltado"></span></td>
				</tr>
				<tr class="aling-left">
					<td>a las: </td>
					<td><span  id="lblhora" class="resaltado"></span></td>
				</tr>
			</table>
			<button type="button" class="btn-danger " >Cancelar</button>
			<button type="button" class="btn-success btnLoad " data-value="Guardar"></button>
		</form>
	</div>
	
</div>