<div class="dialog" id="dlgGuardar">
	<i class="fnClose" title="Salir"></i>
		<h1>Guardando...</h1>
		<hr>
		<form>
			<p class="aling-left">
				<td>Reservar a: </td>
				<td><span id="lblcliente" class="resaltado"></span></td>
			</p >
			<p class="aling-left">
				<td>los servicios: </td>
				<td><span id="lblSer" class="resaltado"></span></td>
			</p>
			<p class="aling-left">
				<td>el: </td>
				<td><span  id="lblfecha" class="resaltado"></span></td>
			</p>
			<p class="aling-left">
				<td>a las: </td>
				<td><span  id="lblhora" class="resaltado"></span></td>
			</p>
		<button type="button" class="btn-success btnLoad " data-value="Guardar">Guardar</button>
		<button type="button" class="btn-danger fnCancel ">Cancelar</button>
		</form>
</div>