<div id="dlgHistorial" class="dialog">
	<span class="icon-cancel"></span>
	<div class="content-popup">
	<div class="close"><a href="#" class="icon-cancel-circled2 close"></a></div>
		<table class="tablas">
			<thead>
				<tr class = "encabezado">
					<th>Opc</th><th>agenda</th><th>Cita</th><th>fecha</th><th>hora</th><th>Servicio</th>
				</tr>
			<thead>
			<tbody>
				<tr class="template">
					<td><span class ="icon-search"></span></td>
					<td class="hisfecha"></td>
					<td class="hishoras"></td>
					<td class="hisIdCita"></td>
					<td class="hisSer"></td>
					<td class="hisagenda"></td>
				</tr>
			<tbody>
		</table>
	</div>
</div>