<div  class="dialog" id="dlgNotas">
	<span class="icon-cancel fnClose"></span>
		<h1>Editando...</h1>
		<hr>
		<input type="text" id="id">
		<div class="iconClass-container icon-left">
			<input type="date" class="txt" id="fecha"  >
			<span class="iconClass-inside  icon-calendar"></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="time" class="txt" id="hora">
			<span class="iconClass-inside  icon-clock"></span>
		</div>
		<div class="iconClass-container icon-left">
		    <textarea id="descripcion" rows="5" cols=""></textarea>
		</div>
		
		<button type="button" class="btn-success btnLoad" data-value="Guardar">Guardar</button>
		<button type="button" class="btn-danger btnLoad" data-value="Eliminar">Eliminar</button>
	</div>
</div>