<div id="dlgUsuarios" class="dialog">
	<span class="icon-cancel"></span>
	<h1 class="heading">Editar usuarios</h1>
	<hr>
	<form id="frmUsuarios">	
		<input type="hidden" name="id" id="id" >
		<div class="iconClass-container icon-left">
			<input type="text" name="nombre" 	id="nombre" placeholder="Introduzca nombre y apellidos." required>
			<span class="iconClass-inside icon-user-1"></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="Email"  name="email" id="email" placeholder="Introduzca email.">
			<span class="iconClass-inside icon-mail-1"></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="tel" name="tel" id="tel" placeholder="Telefono de contacto." >
			<span class="iconClass-inside icon-phone"></span>
		</div>
		<div class="iconClass-container icon-left">
			<input type="text" name="obs" id="obs" placeholder="Introduzca observaciones." >
			<span class="iconClass-inside icon-pencil-1"></span>
		</div>
		<label for = "activa"><input type="checkbox" name ="activa" id ="activa">Usuario desactivado.</label>
		<label for = "admin"><input type="checkbox" name = "admin" id = "admin">Administrador.</label>

		<button type="button" class="btn-success btnLoad aceptar" id="btnGuardarUsuario" data-value="Guardar">Guardar</button>
		<button type="button" class="btn-danger btnLoad cancelar" id="btnEliminarUsuario" data-value="Eliminar">Eliminar</button>

	</form>
</div>